name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Publish .NET Core Project
      run: dotnet publish MickeyWebUtility/MickeyWebUtility/MickeyWebUtility.csproj -c Release -o release --nologo

    - name: Update base href in index.html
      run: |
        sed -i 's|<base href="/" />|<script>document.write("<base href=\"" + (window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1" ? "/" : "/MickeyWebUtility/") + "\" />");</script>|g' release/wwwroot/index.html

    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
      
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Update service worker registration in index.html
      run: |
        sed -i '/navigator.serviceWorker.register/c\        var baseHref = window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1" ? "/" : "/MickeyWebUtility/"; navigator.serviceWorker.register(baseHref + "service-worker.js", { scope: baseHref });' release/wwwroot/index.html

    - name: Print contents of wwwroot
      run: |
        echo "Contents of release/wwwroot:"
        ls -R release/wwwroot

    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'release/wwwroot'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Print deployment URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"